packages:
  - 'apps/*'
  - 'packages/**'

catalog:
  '@radix-ui/react-icons': ^1.3.1
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  '@total-typescript/ts-reset': ^0.6.1
  better-auth: 1.0.4
  next: 15.0.3
  autoprefixer: ^10.4.20
  react: 19.0.0-rc-1631855f-20241023
  react-dom: 19.0.0-rc-1631855f-20241023
  react-hook-form: ^7.53.2
  postcss: ^8.4.49
  tailwindcss: ^3.4.15
  tailwind-merge: ^2.5.4
  tailwindcss-animate: ^1.0.7
  clsx: ^2.1.1
  lucide-react: ^0.461.0
  class-variance-authority: ^0.7.0
  zod: ^3.23.8
  pg: ^8.13.1
